### ISSUE TITLE
Dividing by zero error

### ISSUE THREAD

**Issue by Aapok** [kosumosu/x3daudio1_7_hrtf#1]
Hey!

I tried using your plugin with Arma 3 and just copying the file to the .exe folder did show up in process explorer, but the sound didn't change. Then changing the .dll name to the same on that hooks into the game from the windows system folder crashed the game as soon as any sound needed to be calculated. i.e. Start of the Arma 3 tutorial as soon as i start moving or turn the camera the game crashes and displays some "DIVIDED_BY_ZERO_ERROR". Could this be the HRTF files fault?

**Comment by kosumosu** [comment]
Hi, Aapok!
I had tried the plugin with the latest Arma 3 and can confirm the issue. They changed something in their sound engine. I was investigating this issue in May, so I have already forgotten the details, but my commit says "Found out that current Arma 3 overwrites matrix data what leads to crashes (footsteps sound, maybe?)." So the code must work since May 21. But I haven't compiled new binary yet. I will try to make it so soon.

**Comment by kosumosu** [comment]
> So the code must work since May 21
Excuse me. It seems, it doesn't.

**Comment by Aapok** [comment]
Hey!

Thanks for the respond! I was wondering why the crash happened only after getting "freed" from cutscenes and not before, so it must have something to do with for example movement sounds...

**Comment by Aapok** [comment]
Hey!

Do you think you can make the plugin work with Arma 3 now?

Also would it be possible to change the hrtf files while playing to experience the difference between hrtfs?

**Comment by kosumosu** [comment]
Hello!
I am actually preparing (testing) a new release that fixes broken support for Arma 3.
But if you can compile it by yourself, you can do it right away.

Regarding changing HRTF files on the fly - unfortunately it is not supported. But you can record in-game videos using fraps or whatever you prefer, and compare them later.

**Comment by kosumosu** [comment]
Fixed in [2.0 release](https://github.com/kosumosu/x3daudio1_7_hrtf/releases/tag/v2.0) ;)
